version: '3.8'

services:
  # Service 1: Your FastAPI App
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Notice the host is now 'db', not 'localhost'
      - DATABASE_URL=postgresql://pb:mypassw@db:5432/testdb
      - SECRET_KEY=supersecretkey

  # Service 2: The Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pb
      - POSTGRES_PASSWORD=mypassw
      - POSTGRES_DB=testdb

# This persists your DB data even if you destroy the containers
volumes:
  postgres_data: